### ISSUE TITLE
Kaspersky virus error

### ISSUE THREAD

**Issue by plasmaborg** [carnal0wnage/python_lnk_maker#1]
Hey @carnal0wnage, your project is nice, but Kaspersky detects it is a virus and deletes **immeadietly**. Can you fix the code?

**Comment by TheLawsOfChaos** [comment]
Like.. you understand this project was last updated 4 years ago right?

That said, you should attempt to modify the link.arguments in the .py file. That's probably what it catches on.

**Comment by carnal0wnage** [comment]
Yes as @TheLawsOfChaos mentioned its most likely the link.arguments piece as I'm sure sure everything alerts on the scrobj.dll piece at this point - you should be able to insert pretty much any LoL bin+command (https://lolbas-project.github.io/#)  there and achieve the same thing.
